export { default as IconClose } from './icons/close'
export { default as IconSearch } from './icons/search'
export { default as BackgroundPokemon } from './images/backgroundPokemon.jpg'
export { default as IconStar } from './images/star.png'
export { default as ThumbHeader } from './images/thumbHeader.png'
export { default as ThumbSnorlax } from './images/thumbSnorlax.png'
